apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtg
  template:
    metadata:
      labels:
        app: rtg
    spec:
      containers:
      - image: okteto.dev/rtg:latest
        name: rtg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a1af137f-3a11-4df6-9216-c8a37100ba2c"
        - name: Vless_Path
          value: "/1234567890ll"
        - name: Vmess_UUID
          value: "a1af137f-3a11-4df6-9216-c8a37100ba2c"
        - name: Vmess_Path
          value: "/mm0987654321"
        - name: Share_Path
          value: "/v2link"
